-name: create EC2 and r53
  hosts:local
  connection:local

vars:
 ami_id:
 sg_id:
 zone_id:
 domain_name: "gdaws86s.fun"

instances:
  -mongodb
  -redis
  -mysql
  -rabbitmq

tasks:
  -name: Create ec2 instance
  amazon.ec2.aws.instance:
   name: "{{item}}"
   instance_type: t3.micro
   security_group: "{{sg_id}}"
   image_id: "{{ami_id}}"
   tags:
    Name: "{{item}}"
    loop: "{{instances}}"

  -name: Print the ec2-output
  ansible.builtin.debug:
    msg: "{{ec2_output}}"
