---
- name: Create EC2 and Route53 records
  hosts: localhost
  connection: local

  vars:
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    security_group: sg-0338b6c26e88f5d75
    zone_id: Z09725051OXQ4HS6KAP4
    domain_name: gdaws86s.fun
    instances:
      - mongodb
      - redis

  tasks:
    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        security_group: "{{ security_group }}"
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output

    # - name: Create Route53 DNS records
    #   amazon.aws.route53:
    #     state: present
    #     zone: "{{ zone_id }}"
    #     record: "{{ item.item }}.{{ domain_name }}"
    #     type: A
    #     ttl: 300
    #     value: "{{ item.instances[0].public_ip_address }}"
    #   loop: "{{ ec2_output.results }}"
    #   when: item.instances | length > 0

    - name: Print EC2 output
      ansible.builtin.debug:
        var: ec2_output